################################################################
# dev 环境配置
################################################################

debug = true
devKey = "dev value"

[log]
logFile = "temp/logs/{hostname}_run_application-{date}.log"
errFile = "temp/logs/{hostname}_run_error-{date}.log"
sqlLog = "temp/logs/{hostname}_run_sql-{date}.log"
